version: '2.0'

services:
  backend:
    build: .
    working_dir: /chocolate/app
    user: root
    command: bash -c "yarn && yarn test"
    environment:
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongo
      MONGODB_URL: mongodb
      MONGODB_DATABASE: kalenderbokning
    volumes:
      - ./:/chocolate/app
  mongodb:
    image: mongodb:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    
  mongo-gui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example